# Copyright 2011 The Snappy-Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc
include ../Inc.mk

TARG=misc
GOFILES=\
	quicklz.go\


include $(GOROOT)/src/Make.pkg

